package fastparse.protobuf

object ExampleProtos {

  val addressbook = ProtoFile(List(
    Package(List("tutorial")),
    Import(None, "google/protobuf/timestamp.proto"),
    OptionExpr("java_package", StringConstant("com.example.tutorial")),
    OptionExpr("java_outer_classname", StringConstant("AddressBookProtos")),
    OptionExpr("csharp_namespace", StringConstant("Google.Protobuf.Examples.AddressBook")),
    Message("Person", List(
      Field(repeated = false, "string", "name", 1, List.empty),
      Field(repeated = false, "int32", "id", 2, List.empty),
      Field(repeated = false, "string", "email", 3, List.empty),
      Enum("PhoneType", List(
        EnumField("MOBILE", 0, List.empty),
        EnumField("HOME", 1, List.empty),
        EnumField("WORK", 2, List.empty)
      )),
      Message("PhoneNumber", List(
        Field(repeated = false, "string", "number", 1, List.empty),
        Field(repeated = false, "PhoneType", "type", 2, List.empty)
      )),
      Field(repeated = true, "PhoneNumber", "phones", 4, List.empty),
      Field(repeated = false, "google.protobuf.Timestamp", "last_updated", 5, List.empty)
    )),
    Message("AddressBook", List(
      Field(repeated = true, "Person", "people", 1, List.empty)
    ))
  ))

  val wrappersTest = ProtoFile(List(
    Package(List("wrappers_test")),
    Import(None, "google/protobuf/wrappers.proto"),
    OptionExpr("java_package", StringConstant("com.google.protobuf.wrapperstest")),
    OptionExpr("java_outer_classname", StringConstant("WrappersTestProto")),
    Message("TopLevelMessage", List(
      Field(repeated = false, "int32", "field1", 1, List.empty),
      Field(repeated = false, ".google.protobuf.DoubleValue", "field_double", 2, List.empty),
      Field(repeated = false, ".google.protobuf.FloatValue", "field_float", 3, List.empty),
      Field(repeated = false, ".google.protobuf.Int64Value", "field_int64", 4, List.empty),
      Field(repeated = false, ".google.protobuf.UInt64Value", "field_uint64", 5, List.empty),
      Field(repeated = false, ".google.protobuf.Int32Value", "field_int32", 6, List.empty),
      Field(repeated = false, ".google.protobuf.UInt32Value", "field_uint32", 7, List.empty),
      Field(repeated = false, ".google.protobuf.BoolValue", "field_bool", 8, List.empty),
      Field(repeated = false, ".google.protobuf.StringValue", "field_string", 9, List.empty),
      Field(repeated = false, ".google.protobuf.BytesValue", "field_bytes", 10, List.empty)
    ))
  ))

  val proto3Example = ProtoFile(List(
    Import(Some(Import.PublicModifier), "other.proto"),
    OptionExpr("java_package", StringConstant("com.example.foo")),
    Enum("EnumAllowingAlias", List(OptionExpr("allow_alias", BooleanConstant(true)),
      EnumField("UNKNOWN", 0, List.empty), EnumField("STARTED", 1, List.empty),
      EnumField("RUNNING", 2, List(OptionExpr("(custom_option)", StringConstant("hello world"))))
    )),
    Message("outer", List(
      OptionExpr("(my_option).a", BooleanConstant(true)),
      Message("inner", List(
        Field(repeated = false, "int64", "ival", 1, List.empty)
      )),
      Field(repeated = true, "inner", "inner_message", 2, List.empty),
      Field(repeated = false, "EnumAllowingAlias", "enum_field", 3, List.empty),
      MapField(KeyType.int32, "string", "my_map", 4, List.empty)
    ))
  ))

  val proto3Message = ProtoFile(List(
    Package(List("protobuf", "experimental")),
    OptionExpr("java_package", StringConstant("com.google.protobuf.testing")),
    OptionExpr("java_outer_classname", StringConstant("Proto3Testing")),
    Message("Proto3SpecialFieldName", List(
      Field(repeated = false, "double", "regular_name", 1, List.empty),
      Field(repeated = false, "int32", "cached_size", 2, List.empty),
      Field(repeated = false, "int64", "serialized_size", 3, List.empty),
      Field(repeated = false, "string", "class", 4, List.empty)
    )),
    Message("Proto3Message", List(
      Enum("TestEnum", List(
        EnumField("ZERO", 0, List.empty), EnumField("ONE", 1, List.empty),
        EnumField("TWO", 2, List.empty)
      )),
      Field(repeated = false, "double", "field_double_1", 1, List.empty),
      Field(repeated = false, "float", "field_float_2", 2, List.empty),
      Field(repeated = false, "int64", "field_int64_3", 3, List.empty),
      Field(repeated = false, "uint64", "field_uint64_4", 4, List.empty),
      Field(repeated = false, "int32", "field_int32_5", 5, List.empty),
      Field(repeated = false, "fixed64", "field_fixed64_6", 6, List.empty),
      Field(repeated = false, "fixed32", "field_fixed32_7", 7, List.empty),
      Field(repeated = false, "bool", "field_bool_8", 8, List.empty),
      Field(repeated = false, "string", "field_string_9", 9, List.empty),
      Field(repeated = false, "Proto3Message", "field_message_10", 10, List.empty),
      Field(repeated = false, "bytes", "field_bytes_11", 11, List.empty),
      Field(repeated = false, "uint32", "field_uint32_12", 12, List.empty),
      Field(repeated = false, "TestEnum", "field_enum_13", 13, List.empty),
      Field(repeated = false, "sfixed32", "field_sfixed32_14", 14, List.empty),
      Field(repeated = false, "sfixed64", "field_sfixed64_15", 15, List.empty),
      Field(repeated = false, "sint32", "field_sint32_16", 16, List.empty),
      Field(repeated = false, "sint64", "field_sint64_17", 17, List.empty),
      Field(repeated = true, "double", "field_double_list_18", 18, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "float", "field_float_list_19", 19, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "int64", "field_int64_list_20", 20, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "uint64", "field_uint64_list_21", 21, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "int32", "field_int32_list_22", 22, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "fixed64", "field_fixed64_list_23", 23, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "fixed32", "field_fixed32_list_24", 24, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "bool", "field_bool_list_25", 25, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "string", "field_string_list_26", 26, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "Proto3Message", "field_message_list_27", 27, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "bytes", "field_bytes_list_28", 28, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "uint32", "field_uint32_list_29", 29, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "TestEnum", "field_enum_list_30", 30, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "sfixed32", "field_sfixed32_list_31", 31, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "sfixed64", "field_sfixed64_list_32", 32, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "sint32", "field_sint32_list_33", 33, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "sint64", "field_sint64_list_34", 34, List(OptionExpr("packed", BooleanConstant(false)))),
      Field(repeated = true, "double", "field_double_list_packed_35", 35, List(OptionExpr("packed", BooleanConstant(true)))),
      Field(repeated = true, "float", "field_float_list_packed_36", 36, List(OptionExpr("packed", BooleanConstant(true)))),
      Field(repeated = true, "int64", "field_int64_list_packed_37", 37, List(OptionExpr("packed", BooleanConstant(true)))),
      Field(repeated = true, "uint64", "field_uint64_list_packed_38", 38, List(OptionExpr("packed", BooleanConstant(true)))),
      Field(repeated = true, "int32", "field_int32_list_packed_39", 39, List(OptionExpr("packed", BooleanConstant(true)))),
      Field(repeated = true, "fixed64", "field_fixed64_list_packed_40", 40, List(OptionExpr("packed", BooleanConstant(true)))),
      Field(repeated = true, "fixed32", "field_fixed32_list_packed_41", 41, List(OptionExpr("packed", BooleanConstant(true)))),
      Field(repeated = true, "bool", "field_bool_list_packed_42", 42, List(OptionExpr("packed", BooleanConstant(true)))),
      Field(repeated = true, "uint32", "field_uint32_list_packed_43", 43, List(OptionExpr("packed", BooleanConstant(true)))),
      Field(repeated = true, "TestEnum", "field_enum_list_packed_44", 44, List(OptionExpr("packed", BooleanConstant(true)))),
      Field(repeated = true, "sfixed32", "field_sfixed32_list_packed_45", 45, List(OptionExpr("packed", BooleanConstant(true)))),
      Field(repeated = true, "sfixed64", "field_sfixed64_list_packed_46", 46, List(OptionExpr("packed", BooleanConstant(true)))),
      Field(repeated = true, "sint32", "field_sint32_list_packed_47", 47, List(OptionExpr("packed", BooleanConstant(true)))),
      Field(repeated = true, "sint64", "field_sint64_list_packed_48", 48, List(OptionExpr("packed", BooleanConstant(true)))),
      Oneof("test_oneof", List(
        OneofField("double", "field_double_53", 53, List.empty),
        OneofField("float", "field_float_54", 54, List.empty),
        OneofField("int64", "field_int64_55", 55, List.empty),
        OneofField("uint64", "field_uint64_56", 56, List.empty),
        OneofField("int32", "field_int32_57", 57, List.empty),
        OneofField("fixed64", "field_fixed64_58", 58, List.empty),
        OneofField("fixed32", "field_fixed32_59", 59, List.empty),
        OneofField("bool", "field_bool_60", 60, List.empty),
        OneofField("string", "field_string_61", 61, List.empty),
        OneofField("Proto3Message", "field_message_62", 62, List.empty),
        OneofField("bytes", "field_bytes_63", 63, List.empty),
        OneofField("uint32", "field_uint32_64", 64, List.empty),
        OneofField("sfixed32", "field_sfixed32_65", 65, List.empty),
        OneofField("sfixed64", "field_sfixed64_66", 66, List.empty),
        OneofField("sint32", "field_sint32_67", 67, List.empty),
        OneofField("sint64", "field_sint64_68", 68, List.empty)
      ))
    )),
    Message("Proto3Empty", List.empty),
    Message("Proto3MessageWithMaps", List(
      MapField(KeyType.`bool`, "bool", "field_map_bool_bool_1", 1, List.empty),
      MapField(KeyType.`bool`, "bytes", "field_map_bool_bytes_2", 2, List.empty),
      MapField(KeyType.`bool`, "double", "field_map_bool_double_3", 3, List.empty),
      MapField(KeyType.`bool`, "Proto3Message.TestEnum", "field_map_bool_enum_4", 4, List.empty),
      MapField(KeyType.`bool`, "fixed32", "field_map_bool_fixed32_5", 5, List.empty),
      MapField(KeyType.`bool`, "fixed64", "field_map_bool_fixed64_6", 6, List.empty),
      MapField(KeyType.`bool`, "float", "field_map_bool_float_7", 7, List.empty),
      MapField(KeyType.`bool`, "int32", "field_map_bool_int32_8", 8, List.empty),
      MapField(KeyType.`bool`, "int64", "field_map_bool_int64_9", 9, List.empty),
      MapField(KeyType.`bool`, "Proto3Message", "field_map_bool_message_10", 10, List.empty),
      MapField(KeyType.`bool`, "sfixed32", "field_map_bool_sfixed32_11", 11, List.empty),
      MapField(KeyType.`bool`, "sfixed64", "field_map_bool_sfixed64_12", 12, List.empty),
      MapField(KeyType.`bool`, "sint32", "field_map_bool_sint32_13", 13, List.empty),
      MapField(KeyType.`bool`, "sint64", "field_map_bool_sint64_14", 14, List.empty),
      MapField(KeyType.`bool`, "string", "field_map_bool_string_15", 15, List.empty),
      MapField(KeyType.`bool`, "uint32", "field_map_bool_uint32_16", 16, List.empty),
      MapField(KeyType.`bool`, "uint64", "field_map_bool_uint64_17", 17, List.empty),
      MapField(KeyType.`fixed32`, "bool", "field_map_fixed32_bool_18", 18, List.empty),
      MapField(KeyType.`fixed32`, "bytes", "field_map_fixed32_bytes_19", 19, List.empty),
      MapField(KeyType.`fixed32`, "double", "field_map_fixed32_double_20", 20, List.empty),
      MapField(KeyType.`fixed32`, "Proto3Message.TestEnum", "field_map_fixed32_enum_21", 21, List.empty),
      MapField(KeyType.`fixed32`, "fixed32", "field_map_fixed32_fixed32_22", 22, List.empty),
      MapField(KeyType.`fixed32`, "fixed64", "field_map_fixed32_fixed64_23", 23, List.empty),
      MapField(KeyType.`fixed32`, "float", "field_map_fixed32_float_24", 24, List.empty),
      MapField(KeyType.`fixed32`, "int32", "field_map_fixed32_int32_25", 25, List.empty),
      MapField(KeyType.`fixed32`, "int64", "field_map_fixed32_int64_26", 26, List.empty),
      MapField(KeyType.`fixed32`, "Proto3Message", "field_map_fixed32_message_27", 27, List.empty),
      MapField(KeyType.`fixed32`, "sfixed32", "field_map_fixed32_sfixed32_28", 28, List.empty),
      MapField(KeyType.`fixed32`, "sfixed64", "field_map_fixed32_sfixed64_29", 29, List.empty),
      MapField(KeyType.`fixed32`, "sint32", "field_map_fixed32_sint32_30", 30, List.empty),
      MapField(KeyType.`fixed32`, "sint64", "field_map_fixed32_sint64_31", 31, List.empty),
      MapField(KeyType.`fixed32`, "string", "field_map_fixed32_string_32", 32, List.empty),
      MapField(KeyType.`fixed32`, "uint32", "field_map_fixed32_uint32_33", 33, List.empty),
      MapField(KeyType.`fixed32`, "uint64", "field_map_fixed32_uint64_34", 34, List.empty),
      MapField(KeyType.`fixed64`, "bool", "field_map_fixed64_bool_35", 35, List.empty),
      MapField(KeyType.`fixed64`, "bytes", "field_map_fixed64_bytes_36", 36, List.empty),
      MapField(KeyType.`fixed64`, "double", "field_map_fixed64_double_37", 37, List.empty),
      MapField(KeyType.`fixed64`, "Proto3Message.TestEnum", "field_map_fixed64_enum_38", 38, List.empty),
      MapField(KeyType.`fixed64`, "fixed32", "field_map_fixed64_fixed32_39", 39, List.empty),
      MapField(KeyType.`fixed64`, "fixed64", "field_map_fixed64_fixed64_40", 40, List.empty),
      MapField(KeyType.`fixed64`, "float", "field_map_fixed64_float_41", 41, List.empty),
      MapField(KeyType.`fixed64`, "int32", "field_map_fixed64_int32_42", 42, List.empty),
      MapField(KeyType.`fixed64`, "int64", "field_map_fixed64_int64_43", 43, List.empty),
      MapField(KeyType.`fixed64`, "Proto3Message", "field_map_fixed64_message_44", 44, List.empty),
      MapField(KeyType.`fixed64`, "sfixed32", "field_map_fixed64_sfixed32_45", 45, List.empty),
      MapField(KeyType.`fixed64`, "sfixed64", "field_map_fixed64_sfixed64_46", 46, List.empty),
      MapField(KeyType.`fixed64`, "sint32", "field_map_fixed64_sint32_47", 47, List.empty),
      MapField(KeyType.`fixed64`, "sint64", "field_map_fixed64_sint64_48", 48, List.empty),
      MapField(KeyType.`fixed64`, "string", "field_map_fixed64_string_49", 49, List.empty),
      MapField(KeyType.`fixed64`, "uint32", "field_map_fixed64_uint32_50", 50, List.empty),
      MapField(KeyType.`fixed64`, "uint64", "field_map_fixed64_uint64_51", 51, List.empty),
      MapField(KeyType.`int32`, "bool", "field_map_int32_bool_52", 52, List.empty),
      MapField(KeyType.`int32`, "bytes", "field_map_int32_bytes_53", 53, List.empty),
      MapField(KeyType.`int32`, "double", "field_map_int32_double_54", 54, List.empty),
      MapField(KeyType.`int32`, "Proto3Message.TestEnum", "field_map_int32_enum_55", 55, List.empty),
      MapField(KeyType.`int32`, "fixed32", "field_map_int32_fixed32_56", 56, List.empty),
      MapField(KeyType.`int32`, "fixed64", "field_map_int32_fixed64_57", 57, List.empty),
      MapField(KeyType.`int32`, "float", "field_map_int32_float_58", 58, List.empty),
      MapField(KeyType.`int32`, "int32", "field_map_int32_int32_59", 59, List.empty),
      MapField(KeyType.`int32`, "int64", "field_map_int32_int64_60", 60, List.empty),
      MapField(KeyType.`int32`, "Proto3Message", "field_map_int32_message_61", 61, List.empty),
      MapField(KeyType.`int32`, "sfixed32", "field_map_int32_sfixed32_62", 62, List.empty),
      MapField(KeyType.`int32`, "sfixed64", "field_map_int32_sfixed64_63", 63, List.empty),
      MapField(KeyType.`int32`, "sint32", "field_map_int32_sint32_64", 64, List.empty),
      MapField(KeyType.`int32`, "sint64", "field_map_int32_sint64_65", 65, List.empty),
      MapField(KeyType.`int32`, "string", "field_map_int32_string_66", 66, List.empty),
      MapField(KeyType.`int32`, "uint32", "field_map_int32_uint32_67", 67, List.empty),
      MapField(KeyType.`int32`, "uint64", "field_map_int32_uint64_68", 68, List.empty),
      MapField(KeyType.`int64`, "bool", "field_map_int64_bool_69", 69, List.empty),
      MapField(KeyType.`int64`, "bytes", "field_map_int64_bytes_70", 70, List.empty),
      MapField(KeyType.`int64`, "double", "field_map_int64_double_71", 71, List.empty),
      MapField(KeyType.`int64`, "Proto3Message.TestEnum", "field_map_int64_enum_72", 72, List.empty),
      MapField(KeyType.`int64`, "fixed32", "field_map_int64_fixed32_73", 73, List.empty),
      MapField(KeyType.`int64`, "fixed64", "field_map_int64_fixed64_74", 74, List.empty),
      MapField(KeyType.`int64`, "float", "field_map_int64_float_75", 75, List.empty),
      MapField(KeyType.`int64`, "int32", "field_map_int64_int32_76", 76, List.empty),
      MapField(KeyType.`int64`, "int64", "field_map_int64_int64_77", 77, List.empty),
      MapField(KeyType.`int64`, "Proto3Message", "field_map_int64_message_78", 78, List.empty),
      MapField(KeyType.`int64`, "sfixed32", "field_map_int64_sfixed32_79", 79, List.empty),
      MapField(KeyType.`int64`, "sfixed64", "field_map_int64_sfixed64_80", 80, List.empty),
      MapField(KeyType.`int64`, "sint32", "field_map_int64_sint32_81", 81, List.empty),
      MapField(KeyType.`int64`, "sint64", "field_map_int64_sint64_82", 82, List.empty),
      MapField(KeyType.`int64`, "string", "field_map_int64_string_83", 83, List.empty),
      MapField(KeyType.`int64`, "uint32", "field_map_int64_uint32_84", 84, List.empty),
      MapField(KeyType.`int64`, "uint64", "field_map_int64_uint64_85", 85, List.empty),
      MapField(KeyType.`sfixed32`, "bool", "field_map_sfixed32_bool_86", 86, List.empty),
      MapField(KeyType.`sfixed32`, "bytes", "field_map_sfixed32_bytes_87", 87, List.empty),
      MapField(KeyType.`sfixed32`, "double", "field_map_sfixed32_double_88", 88, List.empty),
      MapField(KeyType.`sfixed32`, "Proto3Message.TestEnum", "field_map_sfixed32_enum_89", 89, List.empty),
      MapField(KeyType.`sfixed32`, "fixed32", "field_map_sfixed32_fixed32_90", 90, List.empty),
      MapField(KeyType.`sfixed32`, "fixed64", "field_map_sfixed32_fixed64_91", 91, List.empty),
      MapField(KeyType.`sfixed32`, "float", "field_map_sfixed32_float_92", 92, List.empty),
      MapField(KeyType.`sfixed32`, "int32", "field_map_sfixed32_int32_93", 93, List.empty),
      MapField(KeyType.`sfixed32`, "int64", "field_map_sfixed32_int64_94", 94, List.empty),
      MapField(KeyType.`sfixed32`, "Proto3Message", "field_map_sfixed32_message_95", 95, List.empty),
      MapField(KeyType.`sfixed32`, "sfixed32", "field_map_sfixed32_sfixed32_96", 96, List.empty),
      MapField(KeyType.`sfixed32`, "sfixed64", "field_map_sfixed32_sfixed64_97", 97, List.empty),
      MapField(KeyType.`sfixed32`, "sint32", "field_map_sfixed32_sint32_98", 98, List.empty),
      MapField(KeyType.`sfixed32`, "sint64", "field_map_sfixed32_sint64_99", 99, List.empty),
      MapField(KeyType.`sfixed32`, "string", "field_map_sfixed32_string_100", 100, List.empty),
      MapField(KeyType.`sfixed32`, "uint32", "field_map_sfixed32_uint32_101", 101, List.empty),
      MapField(KeyType.`sfixed32`, "uint64", "field_map_sfixed32_uint64_102", 102, List.empty),
      MapField(KeyType.`sfixed64`, "bool", "field_map_sfixed64_bool_103", 103, List.empty),
      MapField(KeyType.`sfixed64`, "bytes", "field_map_sfixed64_bytes_104", 104, List.empty),
      MapField(KeyType.`sfixed64`, "double", "field_map_sfixed64_double_105", 105, List.empty),
      MapField(KeyType.`sfixed64`, "Proto3Message.TestEnum", "field_map_sfixed64_enum_106", 106, List.empty),
      MapField(KeyType.`sfixed64`, "fixed32", "field_map_sfixed64_fixed32_107", 107, List.empty),
      MapField(KeyType.`sfixed64`, "fixed64", "field_map_sfixed64_fixed64_108", 108, List.empty),
      MapField(KeyType.`sfixed64`, "float", "field_map_sfixed64_float_109", 109, List.empty),
      MapField(KeyType.`sfixed64`, "int32", "field_map_sfixed64_int32_110", 110, List.empty),
      MapField(KeyType.`sfixed64`, "int64", "field_map_sfixed64_int64_111", 111, List.empty),
      MapField(KeyType.`sfixed64`, "Proto3Message", "field_map_sfixed64_message_112", 112, List.empty),
      MapField(KeyType.`sfixed64`, "sfixed32", "field_map_sfixed64_sfixed32_113", 113, List.empty),
      MapField(KeyType.`sfixed64`, "sfixed64", "field_map_sfixed64_sfixed64_114", 114, List.empty),
      MapField(KeyType.`sfixed64`, "sint32", "field_map_sfixed64_sint32_115", 115, List.empty),
      MapField(KeyType.`sfixed64`, "sint64", "field_map_sfixed64_sint64_116", 116, List.empty),
      MapField(KeyType.`sfixed64`, "string", "field_map_sfixed64_string_117", 117, List.empty),
      MapField(KeyType.`sfixed64`, "uint32", "field_map_sfixed64_uint32_118", 118, List.empty),
      MapField(KeyType.`sfixed64`, "uint64", "field_map_sfixed64_uint64_119", 119, List.empty),
      MapField(KeyType.`sint32`, "bool", "field_map_sint32_bool_120", 120, List.empty),
      MapField(KeyType.`sint32`, "bytes", "field_map_sint32_bytes_121", 121, List.empty),
      MapField(KeyType.`sint32`, "double", "field_map_sint32_double_122", 122, List.empty),
      MapField(KeyType.`sint32`, "Proto3Message.TestEnum", "field_map_sint32_enum_123", 123, List.empty),
      MapField(KeyType.`sint32`, "fixed32", "field_map_sint32_fixed32_124", 124, List.empty),
      MapField(KeyType.`sint32`, "fixed64", "field_map_sint32_fixed64_125", 125, List.empty),
      MapField(KeyType.`sint32`, "float", "field_map_sint32_float_126", 126, List.empty),
      MapField(KeyType.`sint32`, "int32", "field_map_sint32_int32_127", 127, List.empty),
      MapField(KeyType.`sint32`, "int64", "field_map_sint32_int64_128", 128, List.empty),
      MapField(KeyType.`sint32`, "Proto3Message", "field_map_sint32_message_129", 129, List.empty),
      MapField(KeyType.`sint32`, "sfixed32", "field_map_sint32_sfixed32_130", 130, List.empty),
      MapField(KeyType.`sint32`, "sfixed64", "field_map_sint32_sfixed64_131", 131, List.empty),
      MapField(KeyType.`sint32`, "sint32", "field_map_sint32_sint32_132", 132, List.empty),
      MapField(KeyType.`sint32`, "sint64", "field_map_sint32_sint64_133", 133, List.empty),
      MapField(KeyType.`sint32`, "string", "field_map_sint32_string_134", 134, List.empty),
      MapField(KeyType.`sint32`, "uint32", "field_map_sint32_uint32_135", 135, List.empty),
      MapField(KeyType.`sint32`, "uint64", "field_map_sint32_uint64_136", 136, List.empty),
      MapField(KeyType.`sint64`, "bool", "field_map_sint64_bool_137", 137, List.empty),
      MapField(KeyType.`sint64`, "bytes", "field_map_sint64_bytes_138", 138, List.empty),
      MapField(KeyType.`sint64`, "double", "field_map_sint64_double_139", 139, List.empty),
      MapField(KeyType.`sint64`, "Proto3Message.TestEnum", "field_map_sint64_enum_140", 140, List.empty),
      MapField(KeyType.`sint64`, "fixed32", "field_map_sint64_fixed32_141", 141, List.empty),
      MapField(KeyType.`sint64`, "fixed64", "field_map_sint64_fixed64_142", 142, List.empty),
      MapField(KeyType.`sint64`, "float", "field_map_sint64_float_143", 143, List.empty),
      MapField(KeyType.`sint64`, "int32", "field_map_sint64_int32_144", 144, List.empty),
      MapField(KeyType.`sint64`, "int64", "field_map_sint64_int64_145", 145, List.empty),
      MapField(KeyType.`sint64`, "Proto3Message", "field_map_sint64_message_146", 146, List.empty),
      MapField(KeyType.`sint64`, "sfixed32", "field_map_sint64_sfixed32_147", 147, List.empty),
      MapField(KeyType.`sint64`, "sfixed64", "field_map_sint64_sfixed64_148", 148, List.empty),
      MapField(KeyType.`sint64`, "sint32", "field_map_sint64_sint32_149", 149, List.empty),
      MapField(KeyType.`sint64`, "sint64", "field_map_sint64_sint64_150", 150, List.empty),
      MapField(KeyType.`sint64`, "string", "field_map_sint64_string_151", 151, List.empty),
      MapField(KeyType.`sint64`, "uint32", "field_map_sint64_uint32_152", 152, List.empty),
      MapField(KeyType.`sint64`, "uint64", "field_map_sint64_uint64_153", 153, List.empty),
      MapField(KeyType.`string`, "bool", "field_map_string_bool_154", 154, List.empty),
      MapField(KeyType.`string`, "bytes", "field_map_string_bytes_155", 155, List.empty),
      MapField(KeyType.`string`, "double", "field_map_string_double_156", 156, List.empty),
      MapField(KeyType.`string`, "Proto3Message.TestEnum", "field_map_string_enum_157", 157, List.empty),
      MapField(KeyType.`string`, "fixed32", "field_map_string_fixed32_158", 158, List.empty),
      MapField(KeyType.`string`, "fixed64", "field_map_string_fixed64_159", 159, List.empty),
      MapField(KeyType.`string`, "float", "field_map_string_float_160", 160, List.empty),
      MapField(KeyType.`string`, "int32", "field_map_string_int32_161", 161, List.empty),
      MapField(KeyType.`string`, "int64", "field_map_string_int64_162", 162, List.empty),
      MapField(KeyType.`string`, "Proto3Message", "field_map_string_message_163", 163, List.empty),
      MapField(KeyType.`string`, "sfixed32", "field_map_string_sfixed32_164", 164, List.empty),
      MapField(KeyType.`string`, "sfixed64", "field_map_string_sfixed64_165", 165, List.empty),
      MapField(KeyType.`string`, "sint32", "field_map_string_sint32_166", 166, List.empty),
      MapField(KeyType.`string`, "sint64", "field_map_string_sint64_167", 167, List.empty),
      MapField(KeyType.`string`, "string", "field_map_string_string_168", 168, List.empty),
      MapField(KeyType.`string`, "uint32", "field_map_string_uint32_169", 169, List.empty),
      MapField(KeyType.`string`, "uint64", "field_map_string_uint64_170", 170, List.empty),
      MapField(KeyType.`uint32`, "bool", "field_map_uint32_bool_171", 171, List.empty),
      MapField(KeyType.`uint32`, "bytes", "field_map_uint32_bytes_172", 172, List.empty),
      MapField(KeyType.`uint32`, "double", "field_map_uint32_double_173", 173, List.empty),
      MapField(KeyType.`uint32`, "Proto3Message.TestEnum", "field_map_uint32_enum_174", 174, List.empty),
      MapField(KeyType.`uint32`, "fixed32", "field_map_uint32_fixed32_175", 175, List.empty),
      MapField(KeyType.`uint32`, "fixed64", "field_map_uint32_fixed64_176", 176, List.empty),
      MapField(KeyType.`uint32`, "float", "field_map_uint32_float_177", 177, List.empty),
      MapField(KeyType.`uint32`, "int32", "field_map_uint32_int32_178", 178, List.empty),
      MapField(KeyType.`uint32`, "int64", "field_map_uint32_int64_179", 179, List.empty),
      MapField(KeyType.`uint32`, "Proto3Message", "field_map_uint32_message_180", 180, List.empty),
      MapField(KeyType.`uint32`, "sfixed32", "field_map_uint32_sfixed32_181", 181, List.empty),
      MapField(KeyType.`uint32`, "sfixed64", "field_map_uint32_sfixed64_182", 182, List.empty),
      MapField(KeyType.`uint32`, "sint32", "field_map_uint32_sint32_183", 183, List.empty),
      MapField(KeyType.`uint32`, "sint64", "field_map_uint32_sint64_184", 184, List.empty),
      MapField(KeyType.`uint32`, "string", "field_map_uint32_string_185", 185, List.empty),
      MapField(KeyType.`uint32`, "uint32", "field_map_uint32_uint32_186", 186, List.empty),
      MapField(KeyType.`uint32`, "uint64", "field_map_uint32_uint64_187", 187, List.empty),
      MapField(KeyType.`uint64`, "bool", "field_map_uint64_bool_188", 188, List.empty),
      MapField(KeyType.`uint64`, "bytes", "field_map_uint64_bytes_189", 189, List.empty),
      MapField(KeyType.`uint64`, "double", "field_map_uint64_double_190", 190, List.empty),
      MapField(KeyType.`uint64`, "Proto3Message.TestEnum", "field_map_uint64_enum_191", 191, List.empty),
      MapField(KeyType.`uint64`, "fixed32", "field_map_uint64_fixed32_192", 192, List.empty),
      MapField(KeyType.`uint64`, "fixed64", "field_map_uint64_fixed64_193", 193, List.empty),
      MapField(KeyType.`uint64`, "float", "field_map_uint64_float_194", 194, List.empty),
      MapField(KeyType.`uint64`, "int32", "field_map_uint64_int32_195", 195, List.empty),
      MapField(KeyType.`uint64`, "int64", "field_map_uint64_int64_196", 196, List.empty),
      MapField(KeyType.`uint64`, "Proto3Message", "field_map_uint64_message_197", 197, List.empty),
      MapField(KeyType.`uint64`, "sfixed32", "field_map_uint64_sfixed32_198", 198, List.empty),
      MapField(KeyType.`uint64`, "sfixed64", "field_map_uint64_sfixed64_199", 199, List.empty),
      MapField(KeyType.`uint64`, "sint32", "field_map_uint64_sint32_200", 200, List.empty),
      MapField(KeyType.`uint64`, "sint64", "field_map_uint64_sint64_201", 201, List.empty),
      MapField(KeyType.`uint64`, "string", "field_map_uint64_string_202", 202, List.empty),
      MapField(KeyType.`uint64`, "uint32", "field_map_uint64_uint32_203", 203, List.empty),
      MapField(KeyType.`uint64`, "uint64", "field_map_uint64_uint64_204", 204, List.empty)
    ))
  ))
}
